config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  scope "(:locale)", locale: /en|ru/ do
    resources :events
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get 'current', to: 'users#current', as: 'current_user'
    post 'join/:id', to: 'events#join', as: 'join'
    post 'leave/:id', to: 'events#leave', as: 'leave'
    post 'show_type', to: 'events#show_type', as: 'show_type'
    resources :users, except: :index
    resources :sessions, only: [:new, :create, :destroy]
  end
  get '/:locale' => 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id"

  has_and_belongs_to_many :attendances, class_name: "User", optional: true

  belongs_to :event_type

  has_one_attached :image
  validates :date, presence: true
  validates :name, presence: true
  validates :address, presence: true
end

app/models/event_type.rb
class EventType < ApplicationRecord
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :mail, presence: true, uniqueness: true
  has_one_attached :avatar

  has_many :events, dependent: :destroy
  has_and_belongs_to_many :joined_events, class_name: 'Event'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# general application class
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :full_name
  helper_method :initials
  before_action :set_locale
  protect_from_forgery with: :exception

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def full_name(user)
    user.name + ' ' + user.surname
  end

  def initials(user)
    user.name.slice(0, 1) + user.surname.slice(0, 1)
  end

  def authenticate
    unless current_user
      puts 'unauthorized!'
      redirect_to login_path, notice: t('require_login')
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :join, :leave]
  before_action :current_user, only: [:create, :join, :leave]
  before_action :authenticate, only: [:join, :leave, :new, :edit, :destroy]

  
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    param = event_params
    creator = User.find(param[:creator].to_i)
    param[:event_type] = EventType.find_by_id(param[:event_type].to_i)
    param[:creator] = creator
    @event = Event.new(param)
    @event.attendances << creator
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: t('.success') }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: t('.success') }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    id = @event.id
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: t('.success')  }
      format.json { head :no_content }
      format.js { render 'delete.js.erb', locals: {id: id}}
    end
  end

  def join
    @event.attendances << @current_user
    respond_to do |format|
      format.js {render 'joined.js.erb'}
    end
  end

  def leave
    @event.attendances.delete(@current_user)
    respond_to do |format|
      format.js {render 'joined.js.erb'}
    end
  end

  def show_type
    type = params[:event_type]
    unless type == ''
      @events = Event.where(event_type: EventType.find(type.to_i))
    else
      @events = Event.all
    end
    respond_to do |format|
      format.js 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :date, :certain_time, :address, :event_type, :creator, :image)
    end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# sessions controller class
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_mail(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id), notice: t('.success')
    else
      redirect_to login_path, alert: t('.error')
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: t('.logout')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# controller for user management
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_user, only: :current
  before_action :authenticate, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @events = @user.events.last(10)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    # @user.avatar.attach(io: File.open('./app/assets/images/logo2.png'), filename: 'logo2.png') unless @user.avatar.attached?
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: t('.success') }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: t('.success') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    id = @user.id
    @user.destroy
    respond_to do |format|
      if id != @current_user.id
        format.html { redirect_to users_url, notice: t('.success') }
        format.json { head :no_content }
      else
        format.html { redirect_to logout_url, notice: t('.success') }
        format.json { session[:user_id] = nil; head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :mail, :password, :password_confirmation, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attendances.html.erb
<div id="<%= event.id%>" class="col-10">
  <% event.attendances.each do |user| %>
    <% if user.avatar.attached? %>
        <%= link_to image_tag(user.avatar, class: "rounded-lg mini", alt: full_name(user)),user_path(user.id)%>
      <% else %>
        <%= link_to initials(event.creator), user_path(event.creator.id) %>
      <% end%>
  <% end %>
</div>

app/views/events/_event_post.html.erb
<div class="container mb-3">
  <div class="pb-1 border-bottom row">
    <div class ="col">  
      <% if event.creator.avatar.attached?%>
        <%= link_to image_tag(event.creator.avatar, class: "rounded-lg small", alt: "avatar") + full_name(event.creator), user_path(event.creator.id) %>
      <% else %>
        <%= link_to full_name(event.creator), user_path(event.creator.id) %>
      <% end%>
      • <strong><%= event.name %></strong> • <i><small class="text-muted"><%= event.created_at.strftime("%-d %b %Y %H:%M") %></small></i>
    </div>
    <% if event.creator == current_user%>
      <div class = "col-3 float-right" id="control-buttons<%=event.id%>">
        <%= link_to t('.edit'), edit_event_path(event), class: "btn btn-outline-info btn-sm" %>
        <%= link_to t('.delete'), event, method: :delete, remote: true, class: "btn btn-outline-danger btn-sm", onclick: "inactive_on_delete(#{event.id})"%>
      </div>
    <% end %>
  </div>
  <div id="post<%=event.id%>">
    <div class="content pb-1 border-bottom">
      <p>
        <%= event.description %>
      </p>
      <% if event.image.attached?%>
        <img src="<%= (url_for(event.image))%>" class="rounded-lg image" alt="Avatar">
      <%end%>
    </div>

    <div class="details pb-1 border-bottom">
      <p>
        <strong><%= t('.date')%></strong>
        <%= event.date.strftime("%-d %b %Y %H:%M") %>
      </p>

      <p>
        <strong><%= t('.address')%></strong>
        <%= event.address%>
      </p>

      <p>
        <strong><%= t('.type')%></strong>
        <%= event.event_type.name%>
      </p>
    </div>

    <div class="attendances pb-1 border-bottom row">
      <%= render partial: 'events/attendances', locals: {event: event} %>
      <div class="col-2">
        <% if joined%>
          <% unless joined.include? event%>  
            <%= button_to t('.join'), join_path(event.id), method: :post, remote: true,
              class: 'float-right btn btn-success', onclick: "change(#{event.id})", id: "join#{event.id}"%>
            <%= button_to t('.leave'), leave_path(event.id), method: :post, remote: true, 
              class: 'float-right btn btn-danger', onclick: "change(#{event.id})", id: "leave#{event.id}", hidden: true%>
          <% else %>
            <%= button_to t('.join'), join_path(event.id), method: :post, remote: true, 
              class: 'float-right btn btn-success', onclick: "change(#{event.id})", id: "join#{event.id}", hidden: true%>
            <%= button_to t('.leave'), leave_path(event.id), method: :post, remote: true, 
              class: 'float-right btn btn-danger', onclick: "change(#{event.id})", id: "leave#{event.id}"%>
          <% end%>
        <% end%>
      </div>
    </div>
  </div>
</div>

app/views/events/_feed.html.erb
<% events.reverse.each do |event| %>
  <%= current_user ? render(partial: 'events/event_post', locals:{event: event, joined: current_user.joined_events}) 
  :  render(partial: 'events/event_post', locals:{event: event, joined: nil}) %>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, t('.name'), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: "form-control", autocomplete: 'off' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, t('.description'), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :date, t('.date'), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.datetime_field :date, class: "form-control"%>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :address, t('.address'), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :address, class: "form-control" %>
    </div>
  </div>

    <div class="form-group row">
    <%= form.label :event_type, t('.event_type'), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :event_type, options_for_select(EventType.all.map{ |i| [i.name, i.id] }), {} ,{class: "custom-select"} %>
    </div>
  </div>
  <%= form.hidden_field :creator, value: current_user.id%>
  
  <div class="form-group row">
    <%= form.label :image, t('.image'), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.file_field :image%>
    </div>
  </div>
  
  <div class="actions">
    <%= form.submit t('.save'), class: 'btn btn-primary my-1'%>
  </div>
<% end %>

app/views/events/delete.js.erb
document.getElementById("post<%=id%>").innerHTML="<%=escape_javascript content_tag :div,t('.success'), class:"alert alert-info"%>"

app/views/events/edit.html.erb
<h1><%= t('.editing')%></h1>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<h1><%= t('.title')%></h1>
<div class="row d-flex justify-content-center align-items-center">
  <div class="col-8">
    <%= form_with id: 'types', method: :post, url: show_type_path do |f| %>
      <div class="form-group row">
        <%= f.label :event_type, t('.type'), class: "col-sm-2 col-form-label"%>
        <div class="col-sm-6">
          <%= f.select(:event_type, options_for_select(EventType.all.map{ |i| [i.name, i.id] }) ,
          {include_blank: true}, {class: "custom-select"}) %>
        </div>
        <%= f.submit t('.find'), class: 'btn btn-primary my-1 float-right'%>
      </div>
    <% end %>
    <div id="feed">
      <%= render partial: 'events/feed', locals: {events: @events} %>
    </div>
  </div>
</div>

app/views/events/joined.js.erb
document.getElementById("<%= @event.id%>").innerHTML = "<%= escape_javascript render partial: 'attendances', locals: {event:@event}%>"

app/views/events/new.html.erb
<h1><%= t('.title')%></h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<%= render partial: 'events/event_post', locals: {event: @event, joined: current_user.events} %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/show_type.js.erb
document.getElementById("feed").innerHTML = "<%= escape_javascript render partial: 'events/feed', locals: {events: @events}%>"

app/views/layouts/_header.html.erb
<div class="header">
    <%= link_to 'Get Together', events_path, class: 'Logo'%>
    <div class='float-right'>
      <% if session[:user_id]%>
        <%= link_to t('new_event'), new_event_path%>
        <%= link_to t('profile'), user_path(current_user.id) %>
        <%= link_to t('logout'), logout_path%>
      <%else%>
        <%= link_to t('log_in'), login_path%>
        <%= link_to t('sign_up'), new_user_path%>
      <%end%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetTogether</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if notice%>
        <p id="notice" class="alert alert-success"><%= notice %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, t('.name'), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :surname,t('.surname'), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :surname, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :mail,t('.mail'), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.email_field :mail, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :password, t('.password'), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.password_field :password, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :password_confirmation, t('.password_confirm'), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :avatar, t('.avatar'), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.file_field :avatar%>
    </div>
    
  </div>

  <div class="actions">
    <%= form.submit t('.submit'), class: 'btn btn-primary my-1' %>
  </div>
<% end %>

app/views/users/_profile.html.erb
<div class="m-2">
    <% if @user.avatar.attached?%>
        <img src="<%= (url_for(@user.avatar))%>" class="rounded-lg w-100" alt="Avatar">
    <%end%>

    <table class="table">
        <tr>
            <th colspan="2"><%= @user.name + ' ' + @user.surname %></th>
        <tr>
        <tr>
            <td colspan="2"><%= @user.mail %></td>
        </tr>
        <tr>
            <td><%= link_to t('.edit'), edit_user_path(@user), class: 'btn btn-sm btn-primary' %></td>
            <td><%= link_to(t('.destroy'), @user, method: :delete, data: { confirm: t('.confirm') }, class: 'btn btn-danger btn-sm') if @user == current_user %></td>
        </tr>
    </table>
</div>

app/views/users/edit.html.erb
<h1><%= t('.title')%></h1>

<%= render 'form', user: @user %>

<%= link_to t('.show'), @user %>

app/views/users/index.html.erb
<h1><%= t('.title')%></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.mail %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Current User', current_user_path%>
<%= link_to 'Log out', logout_path%>

app/views/users/new.html.erb
<h1><%= t('.title')%></h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-5">
    <%= render 'users/profile' %>
  </div>
  <div class="col-6 m-2">
    <%= render partial: 'events/feed', locals: {events: @events} %>
  </div>
</div>